import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

// Our components
import Header from "@/components/Header";

const jetbrainsMono = JetBrains_Mono({
    subsets: ["latin"],
    weight: ["100", "200", "300","400", "500", "600", "700","800"],
    variable: "--font-jetbrainMono",
});

export const metadata = {
  title: "Portfolio with Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
    <html lang="en">
        <body className={jetbrainsMono.variable}>
        <Header />
        {children}
        </body>
    </html>
  );
}
